---
# tripod.yml
- hosts: core
  gather_facts: False
  roles:
    - role: ios_common
    - role: ios_interface
    - role: ios_ipv4
    - role: ios_ipv4-routing
    - role: ios_fhrp
    - role: ios_eigrp4
      when: '"eigrp" in ipv4.routing'
    - role: ios_recursive-dns-server
    - role: ios_dhcp-server
- hosts: R1
  gather_facts: False
  roles:
    - role: ios_nat
- hosts: core
  gather_facts: False
  roles:
    - role: ios_write
